package com.einssnc.model;
// Generated 2019. 6. 7 ���� 9:32:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BusLocation generated by hbm2java
 */
@Entity
@Table(name = "bus_location", catalog = "simulation")
public class BusLocation implements java.io.Serializable {

	private String vehicleno;
	private BusRoute busRoute;
	private BusStop busStop;
	private double gpslati;
	private double gpslong;
	private String routenm;
	private String routetp;
	private Integer nodeord;

	public BusLocation() {
	}

	public BusLocation(String vehicleno, double gpslati, double gpslong) {
		this.vehicleno = vehicleno;
		this.gpslati = gpslati;
		this.gpslong = gpslong;
	}

	public BusLocation(String vehicleno, BusRoute busRoute, BusStop busStop, double gpslati, double gpslong,
			String routenm, String routetp, Integer nodeord) {
		this.vehicleno = vehicleno;
		this.busRoute = busRoute;
		this.busStop = busStop;
		this.gpslati = gpslati;
		this.gpslong = gpslong;
		this.routenm = routenm;
		this.routetp = routetp;
		this.nodeord = nodeord;
	}

	@Id

	@Column(name = "vehicleno", unique = true, nullable = false, length = 20)
	public String getVehicleno() {
		return this.vehicleno;
	}

	public void setVehicleno(String vehicleno) {
		this.vehicleno = vehicleno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "routeid")
	public BusRoute getBusRoute() {
		return this.busRoute;
	}

	public void setBusRoute(BusRoute busRoute) {
		this.busRoute = busRoute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nodeid")
	public BusStop getBusStop() {
		return this.busStop;
	}

	public void setBusStop(BusStop busStop) {
		this.busStop = busStop;
	}

	@Column(name = "gpslati", nullable = false, precision = 22, scale = 0)
	public double getGpslati() {
		return this.gpslati;
	}

	public void setGpslati(double gpslati) {
		this.gpslati = gpslati;
	}

	@Column(name = "gpslong", nullable = false, precision = 22, scale = 0)
	public double getGpslong() {
		return this.gpslong;
	}

	public void setGpslong(double gpslong) {
		this.gpslong = gpslong;
	}

	@Column(name = "routenm", length = 30)
	public String getRoutenm() {
		return this.routenm;
	}

	public void setRoutenm(String routenm) {
		this.routenm = routenm;
	}

	@Column(name = "routetp", length = 10)
	public String getRoutetp() {
		return this.routetp;
	}

	public void setRoutetp(String routetp) {
		this.routetp = routetp;
	}

	@Column(name = "nodeord")
	public Integer getNodeord() {
		return this.nodeord;
	}

	public void setNodeord(Integer nodeord) {
		this.nodeord = nodeord;
	}

}
