package com.einssnc.model;
// Generated 2019. 6. 5 ���� 10:44:49 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name = "link", catalog = "simulation")
public class Link implements java.io.Serializable {

	private String linkId;
	private Node nodeByFNode;
	private Node nodeByTNode;
	private Character roadUse;
	private Integer lanes;
	private String roadRank;
	private String roadName;
	private Character multiLink;
	private String connect;
	private Integer maxSpd;
	private String restVeh;
	private Integer restW;
	private Integer restH;
	private String remark;
	private String roadType;
	private String roadNo;
	private String xys;
	private Set<Multilink> multilinks = new HashSet<Multilink>(0);
	private Set<RealTimeTrafficJeju> realTimeTrafficJejus = new HashSet<RealTimeTrafficJeju>(0);

	public Link() {
	}

	public Link(String linkId) {
		this.linkId = linkId;
	}

	public Link(String linkId, Node nodeByFNode, Node nodeByTNode, Character roadUse, Integer lanes, String roadRank,
			String roadName, Character multiLink, String connect, Integer maxSpd, String restVeh, Integer restW,
			Integer restH, String remark, String roadType, String roadNo, String xys, Set<Multilink> multilinks,
			Set<RealTimeTrafficJeju> realTimeTrafficJejus) {
		this.linkId = linkId;
		this.nodeByFNode = nodeByFNode;
		this.nodeByTNode = nodeByTNode;
		this.roadUse = roadUse;
		this.lanes = lanes;
		this.roadRank = roadRank;
		this.roadName = roadName;
		this.multiLink = multiLink;
		this.connect = connect;
		this.maxSpd = maxSpd;
		this.restVeh = restVeh;
		this.restW = restW;
		this.restH = restH;
		this.remark = remark;
		this.roadType = roadType;
		this.roadNo = roadNo;
		this.xys = xys;
		this.multilinks = multilinks;
		this.realTimeTrafficJejus = realTimeTrafficJejus;
	}

	@Id

	@Column(name = "link_id", unique = true, nullable = false, length = 10)
	public String getLinkId() {
		return this.linkId;
	}

	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_node")
	public Node getNodeByFNode() {
		return this.nodeByFNode;
	}

	public void setNodeByFNode(Node nodeByFNode) {
		this.nodeByFNode = nodeByFNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "t_node")
	public Node getNodeByTNode() {
		return this.nodeByTNode;
	}

	public void setNodeByTNode(Node nodeByTNode) {
		this.nodeByTNode = nodeByTNode;
	}

	@Column(name = "road_use", length = 1)
	public Character getRoadUse() {
		return this.roadUse;
	}

	public void setRoadUse(Character roadUse) {
		this.roadUse = roadUse;
	}

	@Column(name = "lanes")
	public Integer getLanes() {
		return this.lanes;
	}

	public void setLanes(Integer lanes) {
		this.lanes = lanes;
	}

	@Column(name = "road_rank", length = 3)
	public String getRoadRank() {
		return this.roadRank;
	}

	public void setRoadRank(String roadRank) {
		this.roadRank = roadRank;
	}

	@Column(name = "road_name", length = 50)
	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	@Column(name = "multi_link", length = 1)
	public Character getMultiLink() {
		return this.multiLink;
	}

	public void setMultiLink(Character multiLink) {
		this.multiLink = multiLink;
	}

	@Column(name = "connect", length = 3)
	public String getConnect() {
		return this.connect;
	}

	public void setConnect(String connect) {
		this.connect = connect;
	}

	@Column(name = "max_spd")
	public Integer getMaxSpd() {
		return this.maxSpd;
	}

	public void setMaxSpd(Integer maxSpd) {
		this.maxSpd = maxSpd;
	}

	@Column(name = "rest_veh", length = 5)
	public String getRestVeh() {
		return this.restVeh;
	}

	public void setRestVeh(String restVeh) {
		this.restVeh = restVeh;
	}

	@Column(name = "rest_w")
	public Integer getRestW() {
		return this.restW;
	}

	public void setRestW(Integer restW) {
		this.restW = restW;
	}

	@Column(name = "rest_h")
	public Integer getRestH() {
		return this.restH;
	}

	public void setRestH(Integer restH) {
		this.restH = restH;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "road_type", length = 10)
	public String getRoadType() {
		return this.roadType;
	}

	public void setRoadType(String roadType) {
		this.roadType = roadType;
	}

	@Column(name = "road_no", length = 10)
	public String getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	@Column(name = "xys", length = 65535)
	public String getXys() {
		return this.xys;
	}

	public void setXys(String xys) {
		this.xys = xys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
	public Set<Multilink> getMultilinks() {
		return this.multilinks;
	}

	public void setMultilinks(Set<Multilink> multilinks) {
		this.multilinks = multilinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
	public Set<RealTimeTrafficJeju> getRealTimeTrafficJejus() {
		return this.realTimeTrafficJejus;
	}

	public void setRealTimeTrafficJejus(Set<RealTimeTrafficJeju> realTimeTrafficJejus) {
		this.realTimeTrafficJejus = realTimeTrafficJejus;
	}

}
