package com.einssnc.model;
// Generated 2019. 5. 20 ���� 4:14:02 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name = "link", catalog = "simulation")
public class Link implements java.io.Serializable {

	private String linkId;
	private Node nodeByFNode;
	private Node nodeByTNode;
	private char roadUse;
	private int lanes;
	private String roadRank;
	private String roadName;
	private char multiLink;
	private String connect;
	private Integer maxSpd;
	private String restVeh;
	private Integer restW;
	private Integer restH;
	private String remark;
	private String roadType;
	private String roadNo;
	private Set<NationWideSpeed> nationWideSpeeds = new HashSet<NationWideSpeed>(0);
	private Set<Multilink> multilinks = new HashSet<Multilink>(0);
	private Set<RealTimeTrafficJeju> realTimeTrafficJejus = new HashSet<RealTimeTrafficJeju>(0);

	public Link() {
	}

	public Link(String linkId, Node nodeByFNode, Node nodeByTNode, char roadUse, int lanes, String roadRank,
			String roadName, char multiLink, String connect, String roadType, String roadNo) {
		this.linkId = linkId;
		this.nodeByFNode = nodeByFNode;
		this.nodeByTNode = nodeByTNode;
		this.roadUse = roadUse;
		this.lanes = lanes;
		this.roadRank = roadRank;
		this.roadName = roadName;
		this.multiLink = multiLink;
		this.connect = connect;
		this.roadType = roadType;
		this.roadNo = roadNo;
	}

	public Link(String linkId, Node nodeByFNode, Node nodeByTNode, char roadUse, int lanes, String roadRank,
			String roadName, char multiLink, String connect, Integer maxSpd, String restVeh, Integer restW,
			Integer restH, String remark, String roadType, String roadNo, Set<NationWideSpeed> nationWideSpeeds,
			Set<Multilink> multilinks, Set<RealTimeTrafficJeju> realTimeTrafficJejus) {
		this.linkId = linkId;
		this.nodeByFNode = nodeByFNode;
		this.nodeByTNode = nodeByTNode;
		this.roadUse = roadUse;
		this.lanes = lanes;
		this.roadRank = roadRank;
		this.roadName = roadName;
		this.multiLink = multiLink;
		this.connect = connect;
		this.maxSpd = maxSpd;
		this.restVeh = restVeh;
		this.restW = restW;
		this.restH = restH;
		this.remark = remark;
		this.roadType = roadType;
		this.roadNo = roadNo;
		this.nationWideSpeeds = nationWideSpeeds;
		this.multilinks = multilinks;
		this.realTimeTrafficJejus = realTimeTrafficJejus;
	}

	@Id

	@Column(name = "link_id", unique = true, nullable = false, length = 10)
	public String getLinkId() {
		return this.linkId;
	}

	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_node", nullable = false)
	public Node getNodeByFNode() {
		return this.nodeByFNode;
	}

	public void setNodeByFNode(Node nodeByFNode) {
		this.nodeByFNode = nodeByFNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "t_node", nullable = false)
	public Node getNodeByTNode() {
		return this.nodeByTNode;
	}

	public void setNodeByTNode(Node nodeByTNode) {
		this.nodeByTNode = nodeByTNode;
	}

	@Column(name = "road_use", nullable = false, length = 1)
	public char getRoadUse() {
		return this.roadUse;
	}

	public void setRoadUse(char roadUse) {
		this.roadUse = roadUse;
	}

	@Column(name = "lanes", nullable = false)
	public int getLanes() {
		return this.lanes;
	}

	public void setLanes(int lanes) {
		this.lanes = lanes;
	}

	@Column(name = "road_rank", nullable = false, length = 3)
	public String getRoadRank() {
		return this.roadRank;
	}

	public void setRoadRank(String roadRank) {
		this.roadRank = roadRank;
	}

	@Column(name = "road_name", nullable = false, length = 50)
	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	@Column(name = "multi_link", nullable = false, length = 1)
	public char getMultiLink() {
		return this.multiLink;
	}

	public void setMultiLink(char multiLink) {
		this.multiLink = multiLink;
	}

	@Column(name = "connect", nullable = false, length = 3)
	public String getConnect() {
		return this.connect;
	}

	public void setConnect(String connect) {
		this.connect = connect;
	}

	@Column(name = "max_spd")
	public Integer getMaxSpd() {
		return this.maxSpd;
	}

	public void setMaxSpd(Integer maxSpd) {
		this.maxSpd = maxSpd;
	}

	@Column(name = "rest_veh", length = 5)
	public String getRestVeh() {
		return this.restVeh;
	}

	public void setRestVeh(String restVeh) {
		this.restVeh = restVeh;
	}

	@Column(name = "rest_w")
	public Integer getRestW() {
		return this.restW;
	}

	public void setRestW(Integer restW) {
		this.restW = restW;
	}

	@Column(name = "rest_h")
	public Integer getRestH() {
		return this.restH;
	}

	public void setRestH(Integer restH) {
		this.restH = restH;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "road_type", nullable = false, length = 3)
	public String getRoadType() {
		return this.roadType;
	}

	public void setRoadType(String roadType) {
		this.roadType = roadType;
	}

	@Column(name = "road_no", nullable = false, length = 5)
	public String getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
	public Set<NationWideSpeed> getNationWideSpeeds() {
		return this.nationWideSpeeds;
	}

	public void setNationWideSpeeds(Set<NationWideSpeed> nationWideSpeeds) {
		this.nationWideSpeeds = nationWideSpeeds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
	public Set<Multilink> getMultilinks() {
		return this.multilinks;
	}

	public void setMultilinks(Set<Multilink> multilinks) {
		this.multilinks = multilinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
	public Set<RealTimeTrafficJeju> getRealTimeTrafficJejus() {
		return this.realTimeTrafficJejus;
	}

	public void setRealTimeTrafficJejus(Set<RealTimeTrafficJeju> realTimeTrafficJejus) {
		this.realTimeTrafficJejus = realTimeTrafficJejus;
	}

}
