package com.einssnc.model;
// Generated 2019. 6. 5 ���� 3:01:20 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MultilinkId generated by hbm2java
 */
@Embeddable
public class MultilinkId implements java.io.Serializable {

	private int multiId;
	private String linkId;

	public MultilinkId() {
	}

	public MultilinkId(int multiId, String linkId) {
		this.multiId = multiId;
		this.linkId = linkId;
	}

	@Column(name = "multi_id", nullable = false)
	public int getMultiId() {
		return this.multiId;
	}

	public void setMultiId(int multiId) {
		this.multiId = multiId;
	}

	@Column(name = "link_id", nullable = false, length = 10)
	public String getLinkId() {
		return this.linkId;
	}

	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MultilinkId))
			return false;
		MultilinkId castOther = (MultilinkId) other;

		return (this.getMultiId() == castOther.getMultiId())
				&& ((this.getLinkId() == castOther.getLinkId()) || (this.getLinkId() != null
						&& castOther.getLinkId() != null && this.getLinkId().equals(castOther.getLinkId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMultiId();
		result = 37 * result + (getLinkId() == null ? 0 : this.getLinkId().hashCode());
		return result;
	}

}
