package com.einssnc.model;
// Generated 2019. 6. 5 ���� 10:44:49 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Multilink generated by hbm2java
 */
@Entity
@Table(name = "multilink", catalog = "simulation")
public class Multilink implements java.io.Serializable {

	private MultilinkId id;
	private Link link;
	private String roadRank;
	private String roadType;
	private String roadNo;
	private String roadName;
	private String remark;

	public Multilink() {
	}

	public Multilink(MultilinkId id, Link link) {
		this.id = id;
		this.link = link;
	}

	public Multilink(MultilinkId id, Link link, String roadRank, String roadType, String roadNo, String roadName,
			String remark) {
		this.id = id;
		this.link = link;
		this.roadRank = roadRank;
		this.roadType = roadType;
		this.roadNo = roadNo;
		this.roadName = roadName;
		this.remark = remark;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "multiId", column = @Column(name = "multi_id", nullable = false)),
			@AttributeOverride(name = "linkId", column = @Column(name = "link_id", nullable = false, length = 10)) })
	public MultilinkId getId() {
		return this.id;
	}

	public void setId(MultilinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "link_id", nullable = false, insertable = false, updatable = false)
	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	@Column(name = "road_rank", length = 3)
	public String getRoadRank() {
		return this.roadRank;
	}

	public void setRoadRank(String roadRank) {
		this.roadRank = roadRank;
	}

	@Column(name = "road_type", length = 10)
	public String getRoadType() {
		return this.roadType;
	}

	public void setRoadType(String roadType) {
		this.roadType = roadType;
	}

	@Column(name = "road_no", length = 10)
	public String getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	@Column(name = "road_name", length = 50)
	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
