package com.einssnc.model;
// Generated 2019. 5. 20 ���� 4:14:02 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Multilink generated by hbm2java
 */
@Entity
@Table(name = "multilink", catalog = "simulation")
public class Multilink implements java.io.Serializable {

	private int multiId;
	private Link link;
	private String roadRank;
	private String roadType;
	private String roadNo;
	private String roadName;
	private String remark;

	public Multilink() {
	}

	public Multilink(int multiId, Link link) {
		this.multiId = multiId;
		this.link = link;
	}

	public Multilink(int multiId, Link link, String roadRank, String roadType, String roadNo, String roadName,
			String remark) {
		this.multiId = multiId;
		this.link = link;
		this.roadRank = roadRank;
		this.roadType = roadType;
		this.roadNo = roadNo;
		this.roadName = roadName;
		this.remark = remark;
	}

	@Id

	@Column(name = "multi_id", unique = true, nullable = false)
	public int getMultiId() {
		return this.multiId;
	}

	public void setMultiId(int multiId) {
		this.multiId = multiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "link_id", nullable = false)
	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	@Column(name = "road_rank", length = 3)
	public String getRoadRank() {
		return this.roadRank;
	}

	public void setRoadRank(String roadRank) {
		this.roadRank = roadRank;
	}

	@Column(name = "road_type", length = 3)
	public String getRoadType() {
		return this.roadType;
	}

	public void setRoadType(String roadType) {
		this.roadType = roadType;
	}

	@Column(name = "road_no", length = 10)
	public String getRoadNo() {
		return this.roadNo;
	}

	public void setRoadNo(String roadNo) {
		this.roadNo = roadNo;
	}

	@Column(name = "road_name", length = 50)
	public String getRoadName() {
		return this.roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
