package com.einssnc.model;
// Generated 2019. 5. 23 ���� 10:52:08 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RealTimeTrafficJejuId generated by hbm2java
 */
@Embeddable
public class RealTimeTrafficJejuId implements java.io.Serializable {

	private String linkId;
	private int prcnDt;

	public RealTimeTrafficJejuId() {
	}

	public RealTimeTrafficJejuId(String linkId, int prcnDt) {
		this.linkId = linkId;
		this.prcnDt = prcnDt;
	}

	@Column(name = "link_id", nullable = false, length = 10)
	public String getLinkId() {
		return this.linkId;
	}

	public void setLinkId(String linkId) {
		this.linkId = linkId;
	}

	@Column(name = "prcn_dt", nullable = false)
	public int getPrcnDt() {
		return this.prcnDt;
	}

	public void setPrcnDt(int prcnDt) {
		this.prcnDt = prcnDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RealTimeTrafficJejuId))
			return false;
		RealTimeTrafficJejuId castOther = (RealTimeTrafficJejuId) other;

		return ((this.getLinkId() == castOther.getLinkId()) || (this.getLinkId() != null
				&& castOther.getLinkId() != null && this.getLinkId().equals(castOther.getLinkId())))
				&& (this.getPrcnDt() == castOther.getPrcnDt());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLinkId() == null ? 0 : this.getLinkId().hashCode());
		result = 37 * result + this.getPrcnDt();
		return result;
	}

}
